source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '7.0'
pod 'ChameleonFramework'
pod 'TestFlightSDK'
pod 'AFNetworking', '~> 2.4'
pod 'BitlyForiOS', '1.0.0'
pod 'GoogleAnalytics-iOS-SDK'
pod 'Facebook-iOS-SDK', '3.19.0'
pod 'SDWebImage', '~>3.7.1'
pod 'MDCSwipeToChoose'
pod 'SupportKit'
pod 'MBProgressHUD', '~> 0.8'
pod 'Appirater', '2.0.4'
pod 'Bolts', '1.1.3'
pod 'Parse'
